config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'asanas#home'

  resources :sequences, except: [:edit, :update] do 
    member do
      post 'add_asana'
      post 'remove_asana'
    end
  end

  resources :asanas

  get 'your_asanas', to: 'asanas#your_asanas'
  get 'public_sequences', to: 'sequences#show_public'

  get '/sequences/:id/edit', to: 'sequences#edit', as: "edit_sequence"

  patch '/sequences/:id', to: 'sequences#update'

end

app/models/asana.rb
class Asana < ActiveRecord::Base
	belongs_to :user
end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
	has_many :sequence_entries
	has_many :asanas, through: :sequence_entries
	belongs_to :user
end

app/models/sequence_entry.rb
class SequenceEntry < ActiveRecord::Base
	belongs_to :asana
	belongs_to :sequence
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :sequences

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/asanas_controller.rb
class AsanasController < ApplicationController

	def your_asanas
		@current_user = current_user
		@your_asanas = Asana.where(user: @current_user)

		respond_to do |format|
    	format.html { render :your_asanas }
      format.json { render json: @your_asanas.to_json }
    end
	end

	def home
		@asanas = Asana.all
		@current_user = current_user
	end

	def index
		@current_user = current_user
		@asanas = Asana.where(user: 1)

		respond_to do |format|
    	format.html { render :index }
      format.json { render json: @asanas.to_json }
    end
	end

	def new
		@current_user = current_user
		@asana = Asana.new
	end

	def create
		@current_user = current_user
		@asana = Asana.create!(asana_params.merge(user: @current_user))
		redirect_to your_asanas_path, notice: "Asana created."
	end

	def update
		@current_user = current_user
		@asana = Asana.find(params[:id])
		@asana.update(asana_params.merge(user: @current_user))
		redirect_to your_asanas_path, notice: "Asana updated."
	end

	def show
		@asana = Asana.find(params[:id])
		@owner = @asana.user
		@current_user = current_user
	end

	def destroy
		@current_user = current_user
		@asana = Asana.find(params[:id])
		@asana.destroy
		redirect_to your_asanas_path, notice: "Asana deleted!"
	end

	private
	def asana_params
		params.require(:asana).permit(
			:sanskrit_name,
			:english_name,
			:image_url,
			:user_id )
	end

end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController

	def index
		@current_user = current_user
		@user_sequences = Sequence.where(user: @current_user)
    # @public_sequences = Sequence.all
    @public_sequences = Sequence.where(public: true)
	end

	def show
		@current_user = current_user
		@sequence = Sequence.find(params[:id])
		@asanas = Asana.all
    @asanas_in_seq = @sequence.asanas
    @seq_owner = @sequence.user
    @seq_entries = @sequence.sequence_entries

    respond_to do |format|
      format.html { render :show}
      format.json { render json: @seq_entries.to_json}
    end
    
	end

  def new
    @sequence = Sequence.new
  end

  def edit 
    @sequence = Sequence.find(params[:id])
  end

  def update
    @current_user = current_user
    @sequence = Sequence.find(params[:id])
    @sequence.update(sequence_params)
    redirect_to sequence_path(params[:id]), notice: "Sequence edited."
  end

  def create
  	@current_user = current_user
    @sequence = Sequence.new(sequence_params.merge(user: @current_user))
    if @sequence.save
      redirect_to @sequence
    else
      render :new
    end
  end

  def destroy
    @sequence = Sequence.find(params[:id])
    @sequence.sequence_entries.destroy_all
    @sequence.destroy
    redirect_to sequences_path
  end

  def add_asana
    @sequence = Sequence.find(params[:id])
    if @sequence.sequence_entries.length == 0 
      @sequence.sequence_entries.create(asana_id: params[:asana_id], order: 1)
    else
      @sequence.sequence_entries.create(asana_id: params[:asana_id], order: @sequence.sequence_entries.last.order + 1)
    end
    redirect_to @sequence
  end

  def remove_asana
    @sequence = Sequence.find(params[:id])
    @sequence.sequence_entries.find(params[:seq_id]).destroy
    redirect_to @sequence
  end

  private
  def sequence_params
    params.require(:sequence).permit(:name, :public)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/asanas/_form.html.erb
<%= form_for @asana do |f| %>

	<p><%= f.label :sanskrit_name %>
	<%= f.text_field :sanskrit_name %></p>

	<p><%= f.label :english_name %>
	<%= f.text_field :english_name %></p>

	<p><%= f.label :image_URL %>
	<%= f.text_field :img_url %></p>

	<%= f.submit 'Save', class: 'enter' %>

<% end %>

app/views/asanas/home.html.erb
<div class="jumbotron">
  <div class="header container">
    <h1>Ready Set <span id="om">OM</span></h1>  			
 		<h3>Create, save, and share unique yoga sequences. </h3>

    <h3>
      <% if current_user %>
        <a href="/sequences" class="btn btn-lg btn-primary btn-learn btn-home">Get started &raquo;</a>
      <% else %>
   			 <a href="/sequences" class="btn btn-lg btn-primary btn-learn btn-home">Sign up to get started!</a>
      <% end %>
    </h3>

    <% if notice || alert %>
      <div class="notifs">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
		
		   <%= image_tag("om_calligraphy.svg", :alt => "om", :class => "om_img") %>

  </div>

  </div>
      

app/views/asanas/index.html.erb
<div class="container">
	<% if current_user %>
		<%= react_component('AsanasListUser') %>
	<% else %> 
		<%= react_component('AsanasListNoUser') %>
	<% end %>

	<%= react_component('AsanasList',
	                    { initialAsanas: @asanas },
	                    { prerender: true }) %>
</div>

app/views/asanas/new.html.erb
<div class="container">

	<h2>Add an asana</h2>
	<div id="new_form"><%= render partial: "form" %></div>
	
</div>

app/views/asanas/show.html.erb
<div class="container">

	<h2>Edit an asana</h2>
	
	<div id="new_form"><%= render partial: "form" %></div>

	<%= form_for @asana, method: :delete do |f| %> 
		<%= f.submit 'Delete!', class: 'delete' %>
	<% end %>

</div>

app/views/asanas/your_asanas.html.erb
<div class="container">

  <% if notice || alert %>
    <div class="notifs">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
	<%= react_component('YourAsanasList',
	                    { initialAsanas: @your_asanas },
	                    { prerender: true }) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ready Set OM</title>

  <%= stylesheet_link_tag 'bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-ui.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.hideseek.min.js', 'data-turbolinks-track' => true %>



  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Bree+Serif|Chivo|Arvo|Titillium+Web:400,300|Roboto+Slab:400,300|Droid+Sans', media: 'all', 'data-turbolinks-track' => true %>
  
</head>


 <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">

          <% if current_user %>
            <a class="navbar-brand" href="/">Namaste, <%= current_user.email %>!</a>
            <button class="btn btn-success"><%= link_to 'sign out', destroy_user_session_path, :method => :delete %></button>
           
          <% else %>
            <a class="navbar-brand" href="/">Namaste!</a>
            <button class="btn btn-success"><%= link_to 'sign up', new_user_registration_path %></button>
            <button class="btn btn-success"><%= link_to 'log in', new_user_session_path %></button> 
          <% end %>  
          <span class="nav_buttons_menu">
            <a href="/sequences" class="btn btn-success">Sequences</a>
            <a href="/asanas" class="btn btn-success">Asanas</a>
          </span> 
        </div>         
      </div> 
    </nav>

    <%= yield %>

    <hr>
    
  </body>

  <footer>
    <p>&copy; 2016 <a href="http://www.rebeccaestes.com">Rebecca G. Estes</a></p>
  </footer>

</html>

app/views/sequences/_form.html.erb
<%= form_for(@sequence) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.check_box :public %>
	<%= f.label :public, "Yes, make this sequence public" %>
	<br />
	<%= f.submit 'Save', class: 'enter' %>

<% end %>

app/views/sequences/edit.html.erb
<div class="container">

	<h2>Edit Sequence</h2>

	<%= render partial: "form" %>

	<%= form_for @sequence, method: :delete do |f| %> 
		<%= f.submit 'Delete', class: 'delete' %>
	<% end %>

</div>

app/views/sequences/index.html.erb
<div class="container">
	<h2>
	  Public Sequences
	</h2>

	<ul>
	  <% @public_sequences.each do |sequence| %>
	    <li>
	      <%= link_to sequence.name, sequence %>
	    </li>
	  <% end %>
	</ul>

	<% if current_user %>
		<h2>
		  Your Sequences
		  	<%= link_to "(+)", new_sequence_path %>
		</h2>

		<ul>
		  <% @user_sequences.each do |sequence| %>
		    <li>
		      <%= link_to sequence.name, sequence %>
		    </li>
		  <% end %>
		</ul>
	  <% if @user_sequences.length < 1 %>
	  	You haven't built any sequences yet.
	  <% end %>
	 	<% end %>
</div>

app/views/sequences/new.html.erb
<div class="container">
	<h2>New Sequence</h2>

	<%= form_for(@sequence) do |f| %>

	  <%= f.label :name %>
	  <%= f.text_field :name %><br />
	  <%= f.check_box :public %>
		<%= f.label :public, "Yes, make this sequence public" %>
		<br />
	  <%= f.submit %>

	<% end %>
	
</div>

app/views/sequences/show.html.erb
<div class="container">

  <h2 id="sequence_header"><%= @sequence.name %></h2>

  <span class="hidden-id"><%= @sequence.id %></span>

    <% if @seq_owner == current_user %>
      <% if @sequence.public == true %>
        <p class="instructions">This sequence is <strong>public</strong>. You can change that in the <%= link_to "sequence options", edit_sequence_path(@sequence) %>.</p>
      <% else %>
        <p class="instructions">This sequence is <strong>private</strong>. You can change that in the <%= link_to "sequence options", edit_sequence_path(@sequence) %>.</p>
      <% end %>

      <p>These are the asanas in your sequence. Drag and drop them to reorder.</p>

      <div id="sequence_asanas">

        <!-- Sort from lowest @seq_entries.id to highest. Grab asana_id from that @seq_entries, and display. -->

        <% @seq_entries.each do |entry| %>

          <div class="asana-card your-asana-card seq-card">
            <%= image_tag @asanas_in_seq.find(entry.asana_id).img_url, 
            alt:"#{@asanas_in_seq.find(entry.asana_id).sanskrit_name}" %>
            <div class="card-text">
              <div class="seq-order-id"><%= entry.id %></div>
              <div class="sanskrit"><%= "#{@asanas_in_seq.find(entry.asana_id) .sanskrit_name}" %></div>
              <div class="english"><%= "#{@asanas_in_seq.find(entry.asana_id) .english_name}" %></div>
              <div class="helper delete_from_seq">
                <%= link_to "(x)", remove_asana_sequence_path(@sequence, seq_id: entry.id), method: :post %>
              </div>
            </div>
          </div>
          
        <% end %>

       <%= react_component('SequenceSorter') %>

      </div>

      <hr />

      <h3>Add Asana</h3>

      <%= react_component('AsanaSearch') %>

        <div id="sequence_asanas" class="searchable">

        <% @asanas.each do |asana| %>
          <div class="asana-card your-asana-card">
            <%= image_tag asana.img_url, alt:"#{asana.sanskrit_name}" %>
              <div class="card-text">
                <div class="sanskrit"><%= "#{asana.sanskrit_name}" %></div>
                <div class="english"><%= "#{asana.english_name}" %></div>
                <div class="helper">        
                  <%= link_to "(+)", add_asana_sequence_path(@sequence, asana_id: asana.id), method: :post %>
                </div>
              </div>
            </div>
        <% end %>

      </div>

<!-- 
    <%= react_component('SequenceSelector',
                    { initialAsanas: @asanas},
                    { prerender: true }) %> -->
                    
  <% else %>

    <h4 class="list-top">This sequence was built by <%= @seq_owner.email %>.</h4>
    <div id="sequence_asanas">

      <% @asanas_in_seq.each do |asana| %>
        <div class="asana-card">
          <%= image_tag asana.img_url, alt:"#{asana.sanskrit_name}" %>
            <div class="card-text">
              <div class="sanskrit"><%= "#{asana.sanskrit_name}" %></div>
              <div class="english"><%= "#{asana.english_name}" %></div>
            </div>
          </div>
      <% end %>

    </div>

    <% end %>

  </div>       

app/views/users/login.html.erb
<div class="container">
var AsanasList = React.createClass({

  getInitialState: function() {
      return { 
        logInDisplay: false
      }
  },

  render: function() {
    // return
  }

});

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>